# Generated by Django 5.2 on 2025-06-12 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('necesita_riego', models.BooleanField(default=False)),
                ('riego_automatico', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatosRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad_suelo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_ambiente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_riego', models.DateTimeField(auto_now_add=True)),
                ('cantidad_agua', models.IntegerField(help_text='Cantidad de agua en mililitros')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppHidroZen.planta')),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_minimo_humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia_riego', models.CharField(max_length=50)),
                ('notificaciones', models.BooleanField(default=True)),
                ('planta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AppHidroZen.planta')),
            ],
        ),
    ]
